### ISSUE TITLE
Trying to install api discovery app, get an authorization error

### ISSUE THREAD

**Issue by mattmackenzie** [adobebc/web-apps-sdk#25]
How can I get around this?

![screen shot 2015-05-19 at 2 42 04 pm](https://cloud.githubusercontent.com/assets/653087/7709697/5b6067b8-fe35-11e4-91cd-1f79e6ac7903.png)

**Comment by mtica** [comment]
Have a look at this FAQ - http://docs.businesscatalyst.com/developers/apps/app-faq#authorize-first 

Should the issue persist please open a support ticket to further investigate this issue.

Thanks,
Mihai
